language: cpp
cache: apt
before_script:
   ./tools/travis/lnx-cibuild.before.sh
script:
  ./tools/travis/lnx-cibuild.sh
matrix:
  include:
    - env: ENABLE_STYLE_TESTING=On WITH_GUI=On
      compiler: gcc
## split class vs TOPP tests for GCC (otherwise it will run into time limit of 50min)      
    - env: ENABLE_STYLE_TESTING=Off ENABLE_TOPP_TESTING=On  ENABLE_CLASS_TESTING=Off WITH_GUI=On
      compiler: gcc
    - env: ENABLE_STYLE_TESTING=Off ENABLE_TOPP_TESTING=Off ENABLE_CLASS_TESTING=On  WITH_GUI=On
      compiler: gcc
## clang can run both class+TOPP tests since its faster      
    - env: ENABLE_STYLE_TESTING=Off WITH_GUI=Off
      compiler: clang
    - env: ENABLE_STYLE_TESTING=Off WITH_GUI=On
      compiler: clang
