language: cpp
cache: apt
before_script:
   ./tools/travis/lnx-cibuild.before.sh
script:
  ./tools/travis/lnx-cibuild.sh
matrix:
  include:
## split class vs. TOPP tests for GCC (otherwise it will run into time limit of 50min)
    - env: ENABLE_STYLE_TESTING=OFF ENABLE_TOPP_TESTING=ON ENABLE_CLASS_TESTING=OFF WITH_GUI=ON
      compiler: gcc
    - env: ENABLE_STYLE_TESTING=OFF ENABLE_TOPP_TESTING=ON ENABLE_CLASS_TESTING=OFF WITH_GUI=ON
      compiler: clang
