language: cpp
cache: apt
before_script:
   ./tools/travis/lnx-cibuild.before.sh
script:
  ./tools/travis/lnx-cibuild.sh
matrix:
  include:
    - env: ENABLE_STYLE_TESTING=OFF ENABLE_TOPP_TESTING=ON ENABLE_CLASS_TESTING=OFF WITH_GUI=OFF
      compiler: gcc
